name: School Calendar Sync
on:
  schedule:
    - cron: "0 4 * * *"
    - cron: "0 5 * * 0"
  workflow_dispatch:
    inputs:
      mode:
        description: 'Режим'
        required: true
        default: 'schedule'
        type: choice
        options:
          - schedule
          - holidays

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'
          
      - name: Install
        run: pip install -r requirements.txt
        
      - name: Execute
        env:
          SCHOOL_HOST: ${{ secrets.SCHOOL_HOST }}
          SCHOOL_TOKEN: ${{ secrets.SCHOOL_TOKEN }}
          SCHOOL_USER_UUID: ${{ secrets.SCHOOL_USER_UUID }}
          GOOGLE_CALENDAR_ID: ${{ secrets.GOOGLE_CALENDAR_ID }}
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
        run: |
          MODE="${{ github.event.inputs.mode }}"
          if [ -z "$MODE" ]; then
            if [ "${{ github.event.schedule }}" == "0 5 * * 0" ]; then
              MODE="holidays"
            else
              MODE="schedule"
            fi
          fi
          echo "🚀 Запуск у режимі: $MODE"
          python sync.py --mode $MODE
